FROM python:3.12

WORKDIR /ui
COPY ./ui /ui
COPY requirements.txt /ui
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8501
CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.enableCORS=false"]
